### Register new admin
POST http://localhost:3000/admin/register
Content-Type: application/json

{
  "name": "Admin Jane",
  "email": "adminjane@gmail.com",
  "password": "secureadminpassword",
  "phone": "9876543210"
}


### Get all users
GET http://localhost:3000/admin/users
Content-Type: application/json

### Get details of a specific user
GET http://localhost:3000/admin/users/27638c81-84ad-455a-9ece-52a38cb85850
Content-Type: application/json

### Activate a user
PUT http://localhost:3000/admin/users/a6718f53-56ab-4642-895c-b5b34e338f1d/activate
Content-Type: application/json

### Deactivate a user
PUT http://localhost:3000/admin/users/a6718f53-56ab-4642-895c-b5b34e338f1d/deactivate
Content-Type: application/json

### View all bookings
GET http://localhost:3000/admin/bookings
Content-Type: application/json

### View all payment statuses
GET http://localhost:3000/admin/payments
Content-Type: application/json
