### Get all users
GET http://localhost:3000/api/admin/users
Content-Type: application/json

### Get details of a specific user
GET http://localhost:3000/api/admin/users/:userId
Content-Type: application/json

### Activate a user
PUT http://localhost:3000/api/admin/users/:userId/activate
Content-Type: application/json

### Deactivate a user
PUT http://localhost:3000/api/admin/users/:userId/deactivate
Content-Type: application/json

### View all bookings
GET http://localhost:3000/api/admin/bookings
Content-Type: application/json

### View all payment statuses
GET http://localhost:3000/api/admin/payments
Content-Type: application/json
