###Get All Available Bikes
GET http://localhost:3000/bikes
Content-Type: application/json



###Get Details of a Single Bike
GET http://localhost:3000/bikes/51610907-1e7e-437c-b400-c5cfeec4acd8
Content-Type: application/json


###Add a New Bike
POST http://localhost:3000/bikes
Content-Type: application/json

{
  "model": "FUEL Bike",
  "status": "AVAILABLE",
  "image": "image-url"
}


###Update Bike Information
PUT http://localhost:3000/bikes/395a7764-e6ea-44db-848f-613682b52abb
Content-Type: application/json

{
  "model": "Road Bike",
  "status": "BOOKED",
  "image": "new-image-url"
}


###Soft Delete a Bike
PUT http://localhost:3000/bikes/cab705ba-9995-4ac4-9575-d64967d3eace/soft-delete


###Delete a Bike
DELETE http://localhost:3000/bikes/d5cbcee5-186b-4c17-9516-91eb587b4850


