### Get ticket details by booking ID
GET http://localhost:3000/api/tickets/f7a542c6-b643-4b06-a62a-b1a1f5b2b956
Content-Type: application/json


### Generate a new ticket after booking confirmation
POST http://localhost:3000/api/tickets/3526c0e9-764a-439f-96a5-afad1a513309
Content-Type: application/json

{
  "details": "Bike: Mountain Bike, Model XYZ"
}


### Get all tickets 
GET http://localhost:3000/api/tickets
Content-Type: application/json
