### Get ticket details by booking ID
GET http://localhost:3000/api/tickets/f16cea45-cbdc-4bdc-b3be-bb53287d9c8c
Content-Type: application/json


### Generate a new ticket after booking confirmation
POST http://localhost:3000/api/tickets/f16cea45-cbdc-4bdc-b3be-bb53287d9c8c
Content-Type: application/json

{
  "details": "Bike: Mountain Bike, Model XYZ"
}


### Get all tickets 
GET http://localhost:3000/api/tickets
Content-Type: application/json
